-- --------------------------------------------------------
-- 호스트:                          192.168.30.100
-- 서버 버전:                        10.4.20-MariaDB-1:10.4.20+maria~focal - mariadb.org binary distribution
-- 서버 OS:                        debian-linux-gnu
-- HeidiSQL 버전:                  12.14.0.7165
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_ACS_TKN 구조 내보내기
DROP TABLE IF EXISTS `TB_ACS_TKN`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_ACS_TKN:~0 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_C_ALM 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_C_ALM`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_C_ALM:~51 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_C_CTR 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_C_CTR`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_C_CTR:~80 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_C_INIT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_C_INIT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_C_INIT:~4 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_C_RT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_C_RT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_C_RT:~0 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_D_ALM 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_D_ALM`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_D_ALM:~112 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_D_CTR 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_D_CTR`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_D_CTR:~98 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_D_INIT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_D_INIT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_D_INIT:~10 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_D_RT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_D_RT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_D_RT:~0 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_EVA_G 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_EVA_G`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_EVA_G:~0 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_FACTOR 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_FACTOR`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_FACTOR:~98 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_OPR_HIS 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_OPR_HIS`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_OPR_HIS:~1,476 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_OPR_RT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_OPR_RT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_OPR_RT:~12 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_POST_G_ALM 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_POST_G_ALM`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_POST_G_ALM:~46 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_POST_G_CTR 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_POST_G_CTR`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_POST_G_CTR:~50 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_POST_G_INIT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_POST_G_INIT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_POST_G_INIT:~8 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_POST_G_RT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_POST_G_RT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_POST_G_RT:~6 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_PRE_G_ALM 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_PRE_G_ALM`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_PRE_G_ALM:~66 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_PRE_G_CTR 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_PRE_G_CTR`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_PRE_G_CTR:~122 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_PRE_G_INIT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_PRE_G_INIT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_PRE_G_INIT:~7 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_AI_PRE_G_RT 구조 내보내기
DROP TABLE IF EXISTS `TB_AI_PRE_G_RT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_AI_PRE_G_RT:~6 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_ALM_CTR_HIS 구조 내보내기
DROP TABLE IF EXISTS `TB_ALM_CTR_HIS`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_ALM_CTR_HIS:~182 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_ALM_INFO 구조 내보내기
DROP TABLE IF EXISTS `TB_ALM_INFO`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_ALM_INFO:~31 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_ALM_NTF 구조 내보내기
DROP TABLE IF EXISTS `TB_ALM_NTF`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_ALM_NTF:~452 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_C_RT 구조 내보내기
DROP TABLE IF EXISTS `TB_C_RT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_C_RT:~1,107,219 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_D_RT 구조 내보내기
DROP TABLE IF EXISTS `TB_D_RT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_D_RT:~1,556,754 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_G_RT 구조 내보내기
DROP TABLE IF EXISTS `TB_G_RT`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_G_RT:~1,668,109 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_LGN_HIS 구조 내보내기
DROP TABLE IF EXISTS `TB_LGN_HIS`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_LGN_HIS:~142 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_SYS_CNF 구조 내보내기
DROP TABLE IF EXISTS `TB_SYS_CNF`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_SYS_CNF:~0 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_TAG_DESC 구조 내보내기
DROP TABLE IF EXISTS `TB_TAG_DESC`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_TAG_DESC:~0 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_TAG_MNG 구조 내보내기
DROP TABLE IF EXISTS `TB_TAG_MNG`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_TAG_MNG:~200 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_USR 구조 내보내기
DROP TABLE IF EXISTS `TB_USR`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_USR:~3 rows (대략적) 내보내기

-- WATER_GS 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS `WATER_GS`;
CREATE DATABASE IF NOT EXISTS `WATER_GS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `WATER_GS`;

-- 테이블 WATER_GS.TB_USR_MNG 구조 내보내기
DROP TABLE IF EXISTS `TB_USR_MNG`;
IF NOT EXISTS ;

-- 테이블 데이터 WATER_GS.TB_USR_MNG:~0 rows (대략적) 내보내기
/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
